wiki: Dockerfile: Make it work
ERROR:  Error installing bundler:
        The last version of bundler (>= 0) to support your Ruby &
RubyGems was 2.3.26. Try installing it with `gem install bundler -v
2.3.26`
        bundler requires Ruby version >= 2.6.0. The current ruby version
is 2.4.10.364.

Change-Id: Ib4d1a5c8e169d8c2a6f6ddafdfd0cf3e538e6da0