wiki: Update ruby/setup-ruby to v1.206.0
Error: The current runner (ubuntu-24.04-x64) was detected as self-hosted
because the platform does not match a GitHub-hosted runner image (or
that image is deprecated and no longer supported).

Change-Id: I4c51bd49b3a2b0b791da7731e7831f66c20e2315