Signed builds: Add 'otatools' dependency
Since Android 8, the OTA images are compressed with brotli.
The brotli dependency is not build by default.

On Android 8, the name of the binary for brotli 0.6.x is 'bro'.
Android 9 updated to brotli 1.0.x which changed the binary name to 'brotli'.

As the brotli binary is not build by default, the binary
from the host system will silently be used from $PATH.

The issue was uncovered on Fedora 28 when building Lineage 15.1,
since Fedora 28 already uses brotli 1.0.1 -> no 'bro' binary in $PATH.

'otatools' is a valid Makefile target for 16.0, 15.1 and 14.1.

Fixes this backtrace from build/tools/releasetools/ota_from_target_files.py:

**************************************
Compressing system.new.dat with brotli
Traceback (most recent call last):
  File "./build/tools/releasetools/ota_from_target_files", line 1587, in <module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/ota_from_target_files", line 1542, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "./build/tools/releasetools/ota_from_target_files", line 521, in WriteFullOTAPackage
    system_diff.WriteScript(script, output_zip)
  File "/mnt/android/lineageos/build/make/tools/releasetools/common.py", line 1461, in WriteScript
    self._WriteUpdate(script, output_zip)
  File "/mnt/android/lineageos/build/make/tools/releasetools/common.py", line 1613, in _WriteUpdate
    p = Run(bro_cmd, stdout=subprocess.PIPE)
  File "/mnt/android/lineageos/build/make/tools/releasetools/common.py", line 121, in Run
    return subprocess.Popen(args, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ERROR: OTA update signing failed
**************************************

Change-Id: I6dc3d2a5d5b537ab5487a2278f6ae7c048a695be