wiki: device_build_before_init: `libdw-dev` is required for `android16-6.12` and up
scripts/gendwarfksyms/gendwarfksyms.h:6:10: fatal error: 'dwarf.h' file not found

Change-Id: I52b2e1ef0f3b36f211aa0c00484b1bf33f1b8564